"""empty message

Revision ID: 762028ed7a4e
Revises: 54186d7bfac2
Create Date: 2019-06-05 14:40:59.213054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762028ed7a4e'
down_revision = '54186d7bfac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_comment')
    # ### end Alembic commands ###
